attach(datos_planta)
names(datos_planta)
class(Tratamiento)
class(Raiz)
class(Hojas)
factor(Tratamiento)
summary(datos_planta)
library(tidyverse)
library(tidyselect)
library(rapportools)
boxplot(Raiz ~ Tratamiento)
aov(formula = Raiz ~ Tratamiento, data = datos_planta)
raiz=aov(formula = Raiz ~ Tratamiento, data = datos_planta)
summary(raiz)
TukeyHSD(raiz)
plot(TukeyHSD(raiz))
plot(raiz)
view(raiz
     
boxplot(Tallo ~ Tratamiento)
aov(formula = Tallo ~ Tratamiento, data = datos_planta)
Tallo=aov(formula = Tallo ~ Tratamiento, data = datos_planta)
summary(Tallo)
TukeyHSD(Tallo)
plot(TukeyHSD(Tallo))

boxplot(Hojas ~ Tratamiento)
aov(formula = Hojas ~ Tratamiento, data = datos_planta)
hojas= aov(formula = Hojas ~ Tratamiento, data = datos_planta)
TukeyHSD(hojas)
summary(hojas)
plot(hojas)
plot(TukeyHSD(hojas))


attach(datos_planta)
boxplot(Tuberculos ~ Tratamiento)
aov(Tuberculos ~ Tratamiento, data = datos_planta)
tuberculos= aov(formula = Tuberculos ~ Tratamiento, data = datos_planta)
TukeyHSD(tuberculos)
summary(tuberculos)
plot(hojas)
plot(TukeyHSD(tuberculos))



attach(datos_planta)
boxplot(Tuberculos ~ Tratamiento)
aov(Tuberculos ~ Tratamiento, data = datos_planta)
tuberculos= aov(formula = Tuberculos ~ Tratamiento, data = datos_planta)
TukeyHSD(tuberculos)
summary(tuberculos)
plot(hojas)
plot(TukeyHSD(tuberculos))


attach(datos_planta)
boxplot(`Zona Area` ~ Tratamiento)
aov(`Zona Area` ~ Tratamiento, data = datos_planta)
tuberculos= aov(formula = `Zona Area` ~ Tratamiento, data = datos_planta)
TukeyHSD(tuberculos)
summary(tuberculos)
plot(hojas)
plot(TukeyHSD(tuberculos))


attach(datos_planta)
boxplot(`Zona Radicular` ~ Tratamiento)
aov(`Zona Radicular` ~ Tratamiento, data = datos_planta)
radicular= aov(`Zona Radicular` ~ Tratamiento, data = datos_planta)
TukeyHSD(tuberculos)
summary(tuberculos)
plot(hojas)
plot(TukeyHSD(tuberculos))
